### ISSUE TITLE
Doesn't work in Safari 9

### ISSUE THREAD

**Issue by Haroenv** [Shipow/searchbox#4]
I've been having problems with some things that are seemingly impossible to override. If I find a fix, I'll let you know.

**Comment by Shipow** [comment]
Can you give more details?

**Comment by Haroenv** [comment]
Yesterday the generator showed some of the browser styles still (font-size and border I think), but today the whole panel with results stays empty.

The console gives this error: 

``` js
SyntaxError: JSON Parse error: Single quotes (') are not allowed in JSON
parseapp.js:5
(anonymous function)app.js:5
eachjquery-2.2.0.min.js:1:2777
eachjquery-2.2.0.min.js:1:849
(anonymous function)app.js:4
```

Which is this line: 

``` js
$('.theme-json').each(function(){
  var theme = JSON.parse(JSON.parse(window.getComputedStyle(this,':before').content)); // this one
  themes[theme['search-namespace']] = theme;
});
```

**Comment by Shipow** [comment]
Nice, thank you for pointing this, will have a look!

**Comment by Haroenv** [comment]
When downloaded an example (this is Facebook-style) with another browser, I get this 

![](https://i.imgur.com/RYyW6Tz.png)

Which should look like 

![](https://i.imgur.com/pUO5aCm.png)

**Comment by Shipow** [comment]
Yes, probably related to the first error since sass variables values are not injected in the snippet.

**Comment by Haroenv** [comment]
I noticed that `appearance: none` is marked as invalid, but `-webkit-appearance: none` gives the expected result 

![](https://i.imgur.com/WJGNabe.png)

**Comment by Shipow** [comment]
oh yes, indeed I'm injecting the non autoprefixed version in the download. good catch again.

**Comment by Shipow** [comment]
Should works now!
clear the cache because assets are not rev.

**Comment by Haroenv** [comment]
Looking good now! 👌

**Comment by Shipow** [comment]
Thanks for your help!

**Comment by Haroenv** [comment]
With pleasure!
